# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6828cdad5f5ec438334fde31630bd669d474a36a308f07df99aaf8408966b478ef26853b6b0e12c7823a52e9050f90bc589b26e20ada04e07d43d730467a27ab

test:
  secret_key_base: 60924f8676ecd964d37d263ccb3236f75c76d7637a6cd3e7a220ff04506f50c3025a53e49b144c068ab8e5527eea5c9efb55b2bb7df3e17f95361b903eced842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
